name: subsonic-arubislander 
version: '6.1.3+snap15' 
summary: Your complete, personal media streamer.
description: |
  Stream from your own computer.
  Your media — your terms.
  Enjoy your music and movies everywhere.
  Share with family and friends.

grade: stable 
confinement: strict 

apps:
#  path:
#    command: echo "$PATH"
#  lame:
#    command: lame
#  ffmpeg:
#    command: ffmpeg
#  flac:
#    command: flac

  subsonic:
    command: wrapper.sh
    daemon: forking
    restart-condition: on-abnormal
    plugs: 
      - home
      - network
      - network-bind
      - removable-media
parts:
  subsonic:
    # See 'snapcraft plugins'
    plugin: dump  
    source: https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.3-standalone.tar.gz

  lame:
    plugin: nil
    stage-packages:
      - lame
  
  flac:
    plugin: nil
    stage-packages:
      - flac

  dummy:
    plugin: nil
    after: [ffmpeg]
    stage-packages:
      - try: [libnuma1]
      - libxfixes3
      - libasound2
      - libass5
      - libdrm2
      - libfribidi0
      - libgraphite2-3
      - libharfbuzz0b
      - libopus0
      - libtheora0
      - libva-drm1
      - libva1
      - libva-x11-1
      - libvdpau1
      - libvpx3
      - libx264-148
      - libx265-79
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0

  jre:
    plugin: nil
    stage-packages: 
      - openjdk-8-jre-headless
    override-build: |
      rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-8-openjdk-*/jre/lib/security/cacerts
      #echo "** Deleting $PWD\cacerts"
      #rm cacerts
      #ln -s ../../../../../../../etc/ssl/certs/java/cacerts cacerts
      snapcraftctl build

  launcher:
    plugin: dump
    source: bin
