name: subsonic-arubislander 
version: '6.1.6+snap10'
summary: Your complete, personal media streamer.
description: |
  Stream from your own computer.
  Your media — your terms.
  Enjoy your music and movies everywhere.
  Share with family and friends.

grade: stable 
confinement: strict 
base: core

apps:
#  path:
#    command: echo "$PATH"
#  lame:
#    command: lame
#  ffmpeg:
#    command: ffmpeg
#  flac:
#    command: flac

  subsonic:
    command: wrapper.sh
    daemon: forking
    restart-condition: on-abnormal
    plugs: 
      - home
      - network
      - network-bind
      - removable-media
parts:
  subsonic:
    # See 'snapcraft plugins'
    plugin: dump  
    source: https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.6-standalone.tar.gz
  
  lame:
    plugin: nil
    stage-packages:
      - lame
  
  flac:
    plugin: nil
    stage-packages:
      - flac

  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libglu1-mesa

  # ffmpeg:
  #   build-packages:
  #   - git
  #   - g++
  #   - make
  #   - yasm
  #   - autoconf
  #   - libtool
  #   - cmake
  #   - pkg-config
  #   - automake
  #   - build-essential
  #   - libass-dev
  #   - libfreetype6-dev
  #   - libsdl1.2-dev
  #   - libtheora-dev
  #   - libva-dev
  #   - libvdpau-dev
  #   - libvorbis-dev
  #   - libxcb1-dev
  #   - libxcb-shm0-dev
  #   - libxcb-xfixes0-dev
  #   - texinfo
  #   - zlib1g-dev
  #   - libx264-dev
  #   - libmp3lame-dev
  #   - libopus-dev
  #   - libx265-dev
  #   - libvpx-dev
  #   configflags:
  #   - --prefix=/usr
  #   - --enable-gpl
  #   - --enable-libass
  #   - --enable-libfreetype
  #   - --enable-libmp3lame
  #   - --enable-libopus
  #   - --enable-libtheora
  #   - --enable-libvorbis
  #   - --enable-libvpx
  #   - --enable-libx264
  #   - --enable-libx265
  #   - --enable-nonfree
  #   plugin: autotools
  #   source: git://source.ffmpeg.org/ffmpeg.git
  #   source-type: git
  #   stage-packages:
  #   - libasound2
  #   - libass5
  #   - libdrm2
  #   - libfontconfig1
  #   - libfribidi0
  #   - libgraphite2-3
  #   - libharfbuzz0b
  #   - libmp3lame0
  #   - try: [libnuma1]
  #   - libogg0
  #   - libopus0
  #   - libtheora0
  #   - libva-drm1
  #   - libva1
  #   - libvdpau1
  #   - libvorbis0a
  #   - libvorbisenc2
  #   - libvpx3
  #   - libx11-6
  #   - libx264-148
  #   - libx265-79
  #   - libxau6
  #   - libxcb-shape0
  #   - libxcb-shm0
  #   - libxcb-xfixes0
  #   - libxcb1
  #   - libxdmcp6
  #   - libxext6
      
  jre:
    plugin: nil
    stage-packages: 
      - openjdk-8-jre-headless
    override-build: |
      rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-8-openjdk-*/jre/lib/security/cacerts
      #echo "** Deleting $PWD\cacerts"
      #rm cacerts
      #ln -s ../../../../../../../etc/ssl/certs/java/cacerts cacerts
      snapcraftctl build

  launcher:
    plugin: dump
    source: bin
