name: subsonic-arubislander 
version: '6.1.6+snap37'
summary: Your complete, personal media streamer.
description: |
  Stream from your own computer.
  Your media — your terms.
  Enjoy your music and movies everywhere.
  Share with family and friends.

grade: stable 
confinement: strict 
base: core

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
#  path:
#    command: echo "$PATH"
  # lame:
  #   command: lame
  # ffmpeg:
  #   command: ffmpeg
  # flac:
  #   command: flac

  subsonic:
    command: wrapper.sh
    daemon: forking
    restart-condition: on-abnormal
    plugs: 
      - home
      - network
      - network-bind
      - removable-media
parts:
  subsonic:
    # See 'snapcraft plugins'
    plugin: dump  
    source: https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.6-standalone.tar.gz

  jre:
    plugin: nil
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
    stage-packages: 
      - openjdk-8-jre-headless
      - ffmpeg
      - libglu1-mesa
      - libslang2
      - flac
      - lame
      - freeglut3

  launcher:
    plugin: dump
    source: bin

  # Do not enable parts below
  # Cleanup removes packages necessary for ffmpeg to function properly

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280#heading--cleanup-part
  #
  # cleanup:
  #   after:  # Make this part run last; list all your other parts here
  #     - subsonic
  #     - jre
  #     - launcher
  #   plugin: nil
  #   build-snaps:  # List all content-snaps and base snaps you're using here
  #     - core
  #   override-prime: |
  #     set -eux
  #     for snap in "core"; do  # List all content-snaps and base snaps you're using here
  #         cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
  #     done
